trigger:
- main

pool:
  name: 'Default'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'
    displayName: 'Build project'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    displayName: 'Pack NuGet package'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'

- job: Test
  displayName: 'Test job'
  dependsOn: Build
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--configuration Release'
    displayName: 'Run tests'

- job: Publish
  displayName: 'Publish job'
  dependsOn: Test
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'drop'
      path: '$(Pipeline.Workspace)/drop'

  - script: |
      echo 'Starting apt update'
      sudo apt-get update -y
      echo 'Finished apt update'
      
      echo 'Starting installation of prerequisites'
      sudo apt-get install -y dirmngr gnupg apt-transport-https ca-certificates
      echo 'Finished installation of prerequisites'
      
      echo 'Creating directory for keyrings'
      sudo mkdir -p /etc/apt/keyrings
      echo 'Finished creating directory for keyrings'
      
      echo 'Downloading GPG key for Mono repository'
      sudo wget -qO /etc/apt/keyrings/mono-archive-keyring.gpg https://download.mono-project.com/repo/xamarin.gpg
      echo 'Finished downloading GPG key'
      
      echo 'Adding Mono repository to sources list'
      echo "deb [signed-by=/etc/apt/keyrings/mono-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      echo 'Finished adding Mono repository'
      
      echo 'Updating apt-get again'
      sudo apt-get update -y
      echo 'Finished updating apt-get'
      
      echo 'Starting installation of Mono'
      sudo apt-get install -y mono-devel
      echo 'Finished installation of Mono'
    displayName: 'Install Mono'
  
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      vstsFeed: 'fb34e676-860d-42fb-b174-75c46291e03f'
    displayName: 'Restore NuGet packages (Authenticate to feed)'
  
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Pipeline.Workspace)/drop/*.nupkg'
      publishVstsFeed: 'fb34e676-860d-42fb-b174-75c46291e03f'
    displayName: 'Push NuGet package'

  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(Pipeline.Workspace)/drop'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'fb34e676-860d-42fb-b174-75c46291e03f'
      vstsFeedPackagePublish: 'random'
      versionOption: 'patch'
      patvar: 'PAT'
