trigger:
- main

pool:
  name: 'Default' 
jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet build
    displayName: 'Build project'

- job: Test
  displayName: 'Test job'
  dependsOn: Build
  steps:
  - script: dotnet test
    displayName: 'Run tests'

- job: Publish
  displayName: 'Publish job'
  dependsOn: Test
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
